# Generated by Django 4.0.3 on 2022-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('iban_number', models.CharField(max_length=255, verbose_name='ИИН')),
                ('state_address', models.CharField(max_length=255, verbose_name='Место проживания:')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Весь персонал',
                'verbose_name_plural': 'Весь персонал',
                'ordering': ['name'],
            },
        ),
    ]
